package ast;

public enum TipoE {
  SUMA, RESTA, MUL, DIV, OR, AND, NOT, 
  VAR, IDENTER, IDREAL, IDBOOL, IDBUIT,
  NUM, REAL, BOOL, IDEN, ACCESOARRAY, LLAMADAFUN,
  IGUAL, DISTINTO, MAYOR, MENOR, MAYORIGUAL, MENORIGUAL,
  DECLARACION, FINDECLARACION, DEFAULT,
  TORNAR, ESCRIBE, LEE,
  ARRAY, BLANCO,
  CONDICIONAL, ELSE,
  MIENTRAS, PER,
  ASIGNACION,
  LLAMADA, PARAMETRO, INIPARAMETRO,
  FUNCIO, ARGUMENTOS, INIARGUMENTOS,
  BLOQUE, INIBLOQUE, FINBLOQUE,
  LISTA, MASDIMENSIONES,
  NOU
}
