
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat May 29 17:42:17 CEST 2021
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int ENTER = 4;
  public static final int DISTINTO = 43;
  public static final int POR = 33;
  public static final int CCIERRE = 12;
  public static final int PCIERRE = 10;
  public static final int LCIERRE = 14;
  public static final int ICIERRE = 15;
  public static final int LAP = 13;
  public static final int ESCRIU = 29;
  public static final int CAP = 11;
  public static final int TORNAR = 27;
  public static final int NOU = 3;
  public static final int MENORIGUAL = 41;
  public static final int AND = 36;
  public static final int NOT = 35;
  public static final int IGUAL = 42;
  public static final int OR = 37;
  public static final int PER = 23;
  public static final int BOOL = 5;
  public static final int DIV = 34;
  public static final int FUNCIO = 26;
  public static final int MAYORIGUAL = 40;
  public static final int IAP = 16;
  public static final int EOF = 0;
  public static final int ASIG = 17;
  public static final int FER = 22;
  public static final int error = 1;
  public static final int FALS = 7;
  public static final int BUIT = 28;
  public static final int COMA = 18;
  public static final int MENOS = 32;
  public static final int MENOR = 39;
  public static final int AMB = 25;
  public static final int REAL = 45;
  public static final int MAYOR = 38;
  public static final int EN = 24;
  public static final int ENT = 44;
  public static final int MENTRE = 21;
  public static final int PAP = 9;
  public static final int ELSE = 20;
  public static final int PUNTO = 19;
  public static final int IDREAL = 8;
  public static final int IDEN = 46;
  public static final int CERT = 6;
  public static final int LLEGEIX = 30;
  public static final int VAR = 2;
  public static final int MAS = 31;
}

